server:
  port: 8082
  address: 0.0.0.0

spring:
  application:
    name: account-ms
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-ms-group
      auto-offset-reset: earliest
    producer:
      acks: all

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    ru.t1.apupynin.accountms: DEBUG

metrics:
  threshold:
    ms: 100

cache:
  ttl:
    ms: 60000

security:
  jwt:
    secret: b2hfbXlfZ29kX2l0c19zZWNyZXRfa2V5
    ttl-ms: 3600000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}