services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  client-ms:
    image: client-ms:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: client-ms
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8081:8081"

  account-ms:
    image: account-ms:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: account-ms
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8082:8082"

  credit-ms:
    image: credit-ms:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: credit-ms
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    ports:
      - "8083:8083"